      double precision barn,aml,aml2,al2,amt,
     &pi,pi2,alfa,amp,amh,amhad(3)
      double precision amp2,ap,ap2,amc2
      integer isf20,i2(8),i1(8)
      data barn/0.389379d+6/,
     &aml/0.511000d-3/,
c     &aml/0.105658369d0/,
     &pi/3.1415926d0/,alfa/0.729735d-2/,
     &amp/0.938272d0/
      data amhad/0.1395675d0,0.493646d0,0.7d0/
      data isf20/4/
      data i2/1,1,1,1,1,1,1,1/
      data i1/3,3,3,3,3,3,3,3/

      common/consts/amh,ap,ap2,amp2,amc2,pi2,aml2,al2,amt
