#
# PROG     = $(shell grep -i program *.f | awk '$$2=="program"&&$$4==""{print $$3}' )
#
# SYSLIBS  = -lnsl
#
# CERNLIBS = -lpdflib804 -lmathlib -lphtools -lgeant321 \
# -lpacklib -lkernlib -lpawlib
# CERNLIBS = -lnsl
#
# CLASLIBS = -lbankdefs -lc_bos_io -lfputil \
# -lrecutl -lbos -lfpack -lcc -lmapmanager -lclasutil
 CLASLIBS = -lnsl
#
# F77OPT = -O2 -march=k8 -DLinux -fno-automatic -fno-f2c \
# -funroll-all-loops \
# -fdollar-ok -ffixed-line-length-none -fno-second-underscore \
# -Wunused -Wuninitialized

include $(HOME)/env/include.mk
